version: "3.8"

services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    platform: linux/amd64
    restart: always

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: always
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_pass
    depends_on:
      - guacd
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql
    container_name: guac_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_pass

  rdesktop:
    image: lscr.io/linuxserver/rdesktop:latest
    container_name: rdesktop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    shm_size: "1gb" #optional
    restart: unless-stopped
